// Admin management data: stations, posts, assignments

export const STATIONS = [
  {
    id: "ST-001",
    name: "Kituo Kikuu cha Polisi Dar es Salaam",
    region: "Dar es Salaam",
    district: "Ilala",
    address: "Sokoine Drive, Dar es Salaam",
    phone: "022 211 0001",
    officersCount: 42,
    postsCount: 6,
    status: "active",
    established: "1961",
  },
  {
    id: "ST-002",
    name: "Kituo cha Polisi Kariakoo",
    region: "Dar es Salaam",
    district: "Ilala",
    address: "Mwembe Chai, Kariakoo",
    phone: "022 218 5544",
    officersCount: 28,
    postsCount: 4,
    status: "active",
    established: "1972",
  },
  {
    id: "ST-003",
    name: "Kituo cha Polisi Kinondoni",
    region: "Dar es Salaam",
    district: "Kinondoni",
    address: "Mwenge, Kinondoni",
    phone: "022 277 3311",
    officersCount: 35,
    postsCount: 5,
    status: "active",
    established: "1975",
  },
  {
    id: "ST-004",
    name: "Kituo cha Polisi Temeke",
    region: "Dar es Salaam",
    district: "Temeke",
    address: "Temeke St, Temeke",
    phone: "022 285 9922",
    officersCount: 22,
    postsCount: 3,
    status: "active",
    established: "1978",
  },
  {
    id: "ST-005",
    name: "Kituo cha Polisi Ubungo",
    region: "Dar es Salaam",
    district: "Kinondoni",
    address: "Ubungo Terminal, DSM",
    phone: "022 243 7788",
    officersCount: 20,
    postsCount: 4,
    status: "maintenance",
    established: "1985",
  },
  {
    id: "ST-006",
    name: "Kituo cha Polisi Arusha Mkoani",
    region: "Arusha",
    district: "Arusha",
    address: "Fire Road, Arusha",
    phone: "027 250 1100",
    officersCount: 38,
    postsCount: 5,
    status: "active",
    established: "1963",
  },
  {
    id: "ST-007",
    name: "Kituo cha Polisi Mwanza",
    region: "Mwanza",
    district: "Nyamagana",
    address: "Kenyatta Road, Mwanza",
    phone: "028 250 2200",
    officersCount: 31,
    postsCount: 4,
    status: "active",
    established: "1965",
  },
];

export const POSTS = [
  {
    id: "PT-001",
    name: "Posti ya Mwenge",
    stationId: "ST-003",
    stationName: "Kituo cha Polisi Kinondoni",
    location: "Mwenge Bus Terminal",
    type: "Traffic",
    officersCount: 4,
    status: "active",
    shift: "24/7",
  },
  {
    id: "PT-002",
    name: "Posti ya Ubungo",
    stationId: "ST-005",
    stationName: "Kituo cha Polisi Ubungo",
    location: "Ubungo Terminal",
    type: "Traffic",
    officersCount: 6,
    status: "active",
    shift: "24/7",
  },
  {
    id: "PT-003",
    name: "Posti ya Kariakoo Market",
    stationId: "ST-002",
    stationName: "Kituo cha Polisi Kariakoo",
    location: "Kariakoo Market",
    type: "Patrol",
    officersCount: 3,
    status: "active",
    shift: "06:00 - 22:00",
  },
  {
    id: "PT-004",
    name: "Posti ya Samora Avenue",
    stationId: "ST-001",
    stationName: "Kituo Kikuu cha Polisi DSM",
    location: "Samora Avenue CBD",
    type: "Traffic",
    officersCount: 5,
    status: "active",
    shift: "24/7",
  },
  {
    id: "PT-005",
    name: "Posti ya Mbezi Beach",
    stationId: "ST-003",
    stationName: "Kituo cha Polisi Kinondoni",
    location: "Mbezi Beach Junction",
    type: "Patrol",
    officersCount: 2,
    status: "active",
    shift: "18:00 - 06:00",
  },
  {
    id: "PT-006",
    name: "Posti ya Temeke St",
    stationId: "ST-004",
    stationName: "Kituo cha Polisi Temeke",
    location: "Temeke Road",
    type: "Traffic",
    officersCount: 3,
    status: "inactive",
    shift: "06:00 - 18:00",
  },
  {
    id: "PT-007",
    name: "Posti ya Mandela Road",
    stationId: "ST-001",
    stationName: "Kituo Kikuu cha Polisi DSM",
    location: "Mandela Expressway",
    type: "Traffic",
    officersCount: 4,
    status: "active",
    shift: "24/7",
  },
];

export const ASSIGNMENTS = [
  {
    id: "ASG-001",
    officerId: "TP123456",
    officerName: "Insp. Juma Mwinyi",
    officerRank: "Inspector",
    stationId: "ST-001",
    stationName: "Kituo Kikuu cha Polisi DSM",
    postId: "PT-004",
    postName: "Posti ya Samora Avenue",
    role: "Traffic Officer",
    assignedDate: "01 Jan 2026",
    status: "active",
  },
  {
    id: "ASG-002",
    officerId: "TP234567",
    officerName: "Sgt. Ali Hassan",
    officerRank: "Sergeant",
    stationId: "ST-002",
    stationName: "Kituo cha Polisi Kariakoo",
    postId: "PT-003",
    postName: "Posti ya Kariakoo Market",
    role: "Patrol Officer",
    assignedDate: "15 Feb 2026",
    status: "active",
  },
  {
    id: "ASG-003",
    officerId: "TP345678",
    officerName: "Insp. Grace Mushi",
    officerRank: "Inspector",
    stationId: "ST-003",
    stationName: "Kituo cha Polisi Kinondoni",
    postId: "PT-001",
    postName: "Posti ya Mwenge",
    role: "General Duty",
    assignedDate: "10 Mar 2026",
    status: "active",
  },
  {
    id: "ASG-004",
    officerId: "TP456789",
    officerName: "Sgt. Saidi Juma",
    officerRank: "Sergeant",
    stationId: "ST-004",
    stationName: "Kituo cha Polisi Temeke",
    postId: "PT-006",
    postName: "Posti ya Temeke St",
    role: "Traffic Officer",
    assignedDate: "20 Mar 2026",
    status: "active",
  },
  {
    id: "ASG-005",
    officerId: "TP567890",
    officerName: "Cpl. Mariam Ally",
    officerRank: "Corporal",
    stationId: "ST-002",
    stationName: "Kituo cha Polisi Kariakoo",
    postId: "PT-003",
    postName: "Posti ya Kariakoo Market",
    role: "Patrol Officer",
    assignedDate: "05 Apr 2026",
    status: "active",
  },
  {
    id: "ASG-006",
    officerId: "TP789012",
    officerName: "Sgt. Fatuma Hassan",
    officerRank: "Sergeant",
    stationId: "ST-003",
    stationName: "Kituo cha Polisi Kinondoni",
    postId: "PT-005",
    postName: "Posti ya Mbezi Beach",
    role: "Patrol Officer",
    assignedDate: "12 Apr 2026",
    status: "active",
  },
  {
    id: "ASG-007",
    officerId: "TP678901",
    officerName: "Insp. Hamisi Rashid",
    officerRank: "Inspector",
    stationId: "ST-005",
    stationName: "Kituo cha Polisi Ubungo",
    postId: "PT-002",
    postName: "Posti ya Ubungo",
    role: "General Duty",
    assignedDate: "01 May 2026",
    status: "on-leave",
  },
];

// Unassigned officers (available for assignment)
export const UNASSIGNED_OFFICERS = [
  { id: "TP890123", name: "Cpl. Emmanuel Joseph", rank: "Corporal" },
  { id: "TP901234", name: "Cpl. Zainab Salum", rank: "Corporal" },
  { id: "TP012345", name: "Sgt. David Mtui", rank: "Sergeant" },
];

// General officer citizen search results
export const CITIZEN_RESULT = {
  name: "Juma Khamis Mwinyi",
  photo: null as string | null,
  nida: "1990123456789",
  mobile: "0712 345 678",
  gender: "Male",
  dob: "15 Juni 1990",
  age: 35,
  address: "House No. 45, Mbezi Beach, Kinondoni, Dar es Salaam",
  occupation: "Mfanyabiashara",
  status: "Mtu wa Kawaida",
  statusColor: "#10B981",
  alerts: [] as string[],
  criminalRecord: {
    hasRecord: false,
    cases: 0,
    convictions: 0,
  },
  documents: [
    { type: "Kitambulisho cha Taifa (NIDA)", number: "1990123456789", status: "Sahihi" },
    { type: "Leseni ya Udereva", number: "DL123456789TZ", status: "Sahihi" },
    { type: "Pasipoti", number: "TZ12345678", status: "Sahihi" },
  ],
  vehicles: [
    { plate: "T 003 GHI", model: "Toyota Hilux", color: "White", year: "2022" },
  ],
  history: [
    { date: "10 Mei 2026", type: "Mshiriki wa Shahidi", case: "INC-2026-0341", station: "Kituo Kikuu DSM" },
    { date: "02 Apr 2026", type: "Ripoti ya Wizi", case: "INC-2026-0298", station: "Kituo cha Kinondoni" },
  ],
};
