// Lost Items API — /api/lost-items
// Handles mali zilizopotea at police posts and stations.

import { NextResponse } from "next/server";
import { getServerSession } from "@/lib/auth";
import { requirePermission } from "@/lib/rbac";
import { logAction } from "@/lib/audit-log";
import { getSupabaseAdminAny, isSupabaseEnabled } from "@/lib/supabase/client";
import { errMsg } from "@/lib/api-error";

export async function GET(request: Request) {
  try {
    const session = await getServerSession();
    const check = requirePermission(session, "citizens", "view");
    if (!check.ok) return NextResponse.json({ error: check.error }, { status: check.status });

    const url      = new URL(request.url);
    const search   = url.searchParams.get("search")?.toLowerCase() ?? "";
    const status   = url.searchParams.get("status");
    const category = url.searchParams.get("category");
    const limit    = parseInt(url.searchParams.get("limit") ?? "50");

    if (isSupabaseEnabled()) {
      const admin = getSupabaseAdminAny();
      if (admin) {
        let q = admin.from("lost_items")
          .select("*")
          .order("created_at", { ascending: false })
          .limit(limit);

        if (status && status !== "all") q = q.eq("status", status);
        if (category && category !== "all") q = q.eq("category", category);
        if (search) q = q.or(
          `description.ilike.%${search}%,serial_no.ilike.%${search}%,owner_name.ilike.%${search}%,item_number.ilike.%${search}%`
        );

        const { data, error, count } = await q;
        if (error) throw error;
        return NextResponse.json({ ok: true, data: data ?? [], total: count ?? data?.length ?? 0 });
      }
    }
    return NextResponse.json({ ok: true, data: [], total: 0 });
  } catch (err) {
    return NextResponse.json({ error: errMsg(err) }, { status: 500 });
  }
}

export async function POST(request: Request) {
  try {
    const session = await getServerSession();
    const check = requirePermission(session, "citizens", "create");
    if (!check.ok) return NextResponse.json({ error: check.error }, { status: check.status });

    const body = await request.json().catch(() => ({}));
    if (!body.description) {
      return NextResponse.json({ error: "Maelezo ya mali yanahitajika" }, { status: 400 });
    }

    if (isSupabaseEnabled()) {
      const admin = getSupabaseAdminAny();
      if (admin) {
        const { data, error } = await admin.from("lost_items").insert({
          item_number:     "",  // auto-generated by trigger
          category:        body.category || "mali-nyingine",
          description:     body.description,
          serial_no:       body.serialNo || null,
          device_no:       body.deviceNo || null,
          brand:           body.brand || null,
          color:           body.color || null,
          estimated_value: body.estimatedValue || null,
          status:          "searching",
          owner_name:      body.ownerName || null,
          owner_phone:     body.ownerPhone || null,
          owner_nida:      body.ownerNida || null,
          reporter_name:   body.reporterName || body.ownerName || null,
          reporter_phone:  body.reporterPhone || body.ownerPhone || null,
          reported_date:   new Date().toISOString().split("T")[0],
          station_name:    body.station || session?.user?.station || null,
          officer_name:    session?.user?.name || body.reportedBy || null,
        }).select().single();

        if (error) throw error;
        await logAction(session, "lost_item_reported", "lost_items", data.id, {
          category: body.category, description: body.description,
        });
        return NextResponse.json({ ok: true, data }, { status: 201 });
      }
    }

    // Offline fallback — return generated ID so offline sync works
    return NextResponse.json({
      ok: true,
      data: { id: `LI-${Date.now()}`, item_number: `LI-${new Date().getFullYear()}-OFFLINE` },
    }, { status: 201 });
  } catch (err) {
    return NextResponse.json({ error: errMsg(err) }, { status: 500 });
  }
}
