// Lost Items API — migrated to withAuth() for centralized auth + audit
// Handles mali zilizopotea at police posts and stations.
//
// Migration: getServerSession + requirePermission + logAction → withAuth
// (audit logging is now automatic for POST)
import { withAuth } from "@/lib/api-guard";
import { isDbEnabled } from "@/lib/db/client";

// GET /api/lost-items → list lost items (filter: search, status, category)
export const GET = withAuth("citizens", "view", async ({ db, searchParams }) => {
  const search   = searchParams.get("search")?.toLowerCase() ?? "";
  const status   = searchParams.get("status");
  const category = searchParams.get("category");
  const limit    = parseInt(searchParams.get("limit") ?? "50");

  if (!isDbEnabled()) {
    return { ok: true, data: [], total: 0 };
  }

  let q = db
    .from("lost_items")
    .select("*")
    .order("created_at", { ascending: false })
    .limit(limit);

  if (status && status !== "all")     q = q.eq("status", status);
  if (category && category !== "all") q = q.eq("category", category);
  if (search) {
    q = q.or(
      `description.ilike.%${search}%,serial_no.ilike.%${search}%,owner_name.ilike.%${search}%,item_number.ilike.%${search}%`
    );
  }

  const { data, error, count } = await q;
  if (error) throw error;
  return {
    ok: true,
    data: data ?? [],
    total: count ?? data?.length ?? 0,
  };
});

// POST /api/lost-items → create a lost item report (auto-audited)
export const POST = withAuth("citizens", "create", async ({ body, session, db }) => {
  if (!body.description) {
    return { ok: false, error: "Maelezo ya mali yanahitajika", status: 400 };
  }

  if (!isDbEnabled()) {
    // Offline fallback — return generated ID so offline sync works
    return {
      ok: true,
      data: {
        id: `LI-${Date.now()}`,
        item_number: `LI-${new Date().getFullYear()}-OFFLINE`,
      },
      status: 201,
    };
  }

  const { data, error } = await db.from("lost_items").insert({
    item_number:     "",  // auto-generated by trigger
    category:        body.category || "mali-nyingine",
    description:     body.description,
    serial_no:       body.serialNo || null,
    device_no:       body.deviceNo || null,
    brand:           body.brand || null,
    color:           body.color || null,
    estimated_value: body.estimatedValue || null,
    status:          "searching",
    owner_name:      body.ownerName || null,
    owner_phone:     body.ownerPhone || null,
    owner_nida:      body.ownerNida || null,
    reporter_name:   body.reporterName || body.ownerName || null,
    reporter_phone:  body.reporterPhone || body.ownerPhone || null,
    reported_date:   new Date().toISOString().split("T")[0],
    station_name:    body.station || session?.user?.station || null,
    officer_name:    session?.user?.name || body.reportedBy || null,
  }).select().single();

  if (error) throw error;
  return { ok: true, data, status: 201 };
});
